[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.17"
solana-sdk = "1.17"
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
solana-transaction-status = "1.17.10"
